name: stich
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  collection: ^1.19.1
  dart_openai: ^5.1.0
  envied: ^1.1.1
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  envied_generator: ^1.1.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  fonts:
    - family: PlaywriteUSTrad
      fonts:
        - asset: assets/fonts/PlaywriteUSTrad-Regular.ttf
        - asset: assets/fonts/PlaywriteUSTrad-Light.ttf
        - asset: assets/fonts/PlaywriteUSTrad-Thin.ttf
        - asset: assets/fonts/PlaywriteUSTrad-ExtraLight.ttf